// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb.proto

/*
	Package pb is a generated protocol buffer package.

	It is generated from these files:
		pb.proto

	It has these top-level messages:
		Heartbeat
		InitUploadReq
		InitUploadRsp
		UploadReq
		UploadRsp
		UploadCompleteReq
		UploadCompleteRsp
		UploadContinue
		SysUsage
*/
package pb

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	_ "github.com/gogo/protobuf/gogoproto"

	io "io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Code int32

const (
	CodeSucc            Code = 0
	CodeBusy            Code = 1
	CodeMissing         Code = 2
	CodeInvalidChunk    Code = 3
	CodeInvalidChecksum Code = 4
	CodeOSSError        Code = 5
	CodeMaxRetries      Code = 6
)

var Code_name = map[int32]string{
	0: "CodeSucc",
	1: "CodeBusy",
	2: "CodeMissing",
	3: "CodeInvalidChunk",
	4: "CodeInvalidChecksum",
	5: "CodeOSSError",
	6: "CodeMaxRetries",
}
var Code_value = map[string]int32{
	"CodeSucc":            0,
	"CodeBusy":            1,
	"CodeMissing":         2,
	"CodeInvalidChunk":    3,
	"CodeInvalidChecksum": 4,
	"CodeOSSError":        5,
	"CodeMaxRetries":      6,
}

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}
func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}
func (x *Code) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Code_value, data, "Code")
	if err != nil {
		return err
	}
	*x = Code(value)
	return nil
}
func (Code) EnumDescriptor() ([]byte, []int) { return fileDescriptorPb, []int{0} }

type Cmd int32

const (
	CmdHB                Cmd = 0
	CmdUploadInit        Cmd = 1
	CmdUploadInitRsp     Cmd = 2
	CmdUpload            Cmd = 3
	CmdUploadRsp         Cmd = 4
	CmdUploadComplete    Cmd = 5
	CmdUploadCompleteRsp Cmd = 6
	CmdUploadContinue    Cmd = 7
	CmdSysUsage          Cmd = 8
)

var Cmd_name = map[int32]string{
	0: "CmdHB",
	1: "CmdUploadInit",
	2: "CmdUploadInitRsp",
	3: "CmdUpload",
	4: "CmdUploadRsp",
	5: "CmdUploadComplete",
	6: "CmdUploadCompleteRsp",
	7: "CmdUploadContinue",
	8: "CmdSysUsage",
}
var Cmd_value = map[string]int32{
	"CmdHB":                0,
	"CmdUploadInit":        1,
	"CmdUploadInitRsp":     2,
	"CmdUpload":            3,
	"CmdUploadRsp":         4,
	"CmdUploadComplete":    5,
	"CmdUploadCompleteRsp": 6,
	"CmdUploadContinue":    7,
	"CmdSysUsage":          8,
}

func (x Cmd) Enum() *Cmd {
	p := new(Cmd)
	*p = x
	return p
}
func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}
func (x *Cmd) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Cmd_value, data, "Cmd")
	if err != nil {
		return err
	}
	*x = Cmd(value)
	return nil
}
func (Cmd) EnumDescriptor() ([]byte, []int) { return fileDescriptorPb, []int{1} }

type Heartbeat struct {
	Mac              string `protobuf:"bytes,1,opt,name=mac" json:"mac"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{0} }

func (m *Heartbeat) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type InitUploadReq struct {
	Seq              uint64 `protobuf:"varint,1,opt,name=seq" json:"seq"`
	ContentType      string `protobuf:"bytes,2,opt,name=contentType" json:"contentType"`
	ContentLength    int64  `protobuf:"varint,3,opt,name=contentLength" json:"contentLength"`
	ChunkCount       int32  `protobuf:"varint,4,opt,name=chunkCount" json:"chunkCount"`
	ModTime          int64  `protobuf:"varint,5,opt,name=modTime" json:"modTime"`
	Camera           string `protobuf:"bytes,6,opt,name=camera" json:"camera"`
	Mac              string `protobuf:"bytes,7,opt,name=mac" json:"mac"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *InitUploadReq) Reset()                    { *m = InitUploadReq{} }
func (m *InitUploadReq) String() string            { return proto.CompactTextString(m) }
func (*InitUploadReq) ProtoMessage()               {}
func (*InitUploadReq) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{1} }

func (m *InitUploadReq) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *InitUploadReq) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *InitUploadReq) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *InitUploadReq) GetChunkCount() int32 {
	if m != nil {
		return m.ChunkCount
	}
	return 0
}

func (m *InitUploadReq) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *InitUploadReq) GetCamera() string {
	if m != nil {
		return m.Camera
	}
	return ""
}

func (m *InitUploadReq) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type InitUploadRsp struct {
	Seq              uint64 `protobuf:"varint,1,opt,name=seq" json:"seq"`
	ID               uint64 `protobuf:"varint,2,opt,name=id" json:"id"`
	Code             Code   `protobuf:"varint,3,opt,name=code,enum=pb.Code" json:"code"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *InitUploadRsp) Reset()                    { *m = InitUploadRsp{} }
func (m *InitUploadRsp) String() string            { return proto.CompactTextString(m) }
func (*InitUploadRsp) ProtoMessage()               {}
func (*InitUploadRsp) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{2} }

func (m *InitUploadRsp) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *InitUploadRsp) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *InitUploadRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return CodeSucc
}

type UploadReq struct {
	ID               uint64 `protobuf:"varint,1,opt,name=id" json:"id"`
	Index            int32  `protobuf:"varint,2,opt,name=index" json:"index"`
	Data             []byte `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadReq) Reset()                    { *m = UploadReq{} }
func (m *UploadReq) String() string            { return proto.CompactTextString(m) }
func (*UploadReq) ProtoMessage()               {}
func (*UploadReq) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{3} }

func (m *UploadReq) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UploadReq) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *UploadReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadRsp struct {
	ID               uint64 `protobuf:"varint,1,opt,name=id" json:"id"`
	Index            int32  `protobuf:"varint,2,opt,name=index" json:"index"`
	Code             Code   `protobuf:"varint,3,opt,name=code,enum=pb.Code" json:"code"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadRsp) Reset()                    { *m = UploadRsp{} }
func (m *UploadRsp) String() string            { return proto.CompactTextString(m) }
func (*UploadRsp) ProtoMessage()               {}
func (*UploadRsp) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{4} }

func (m *UploadRsp) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UploadRsp) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *UploadRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return CodeSucc
}

type UploadCompleteReq struct {
	ID               uint64 `protobuf:"varint,1,opt,name=id" json:"id"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadCompleteReq) Reset()                    { *m = UploadCompleteReq{} }
func (m *UploadCompleteReq) String() string            { return proto.CompactTextString(m) }
func (*UploadCompleteReq) ProtoMessage()               {}
func (*UploadCompleteReq) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{5} }

func (m *UploadCompleteReq) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type UploadCompleteRsp struct {
	ID               uint64 `protobuf:"varint,1,opt,name=id" json:"id"`
	Code             Code   `protobuf:"varint,2,opt,name=code,enum=pb.Code" json:"code"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadCompleteRsp) Reset()                    { *m = UploadCompleteRsp{} }
func (m *UploadCompleteRsp) String() string            { return proto.CompactTextString(m) }
func (*UploadCompleteRsp) ProtoMessage()               {}
func (*UploadCompleteRsp) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{6} }

func (m *UploadCompleteRsp) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UploadCompleteRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return CodeSucc
}

type UploadContinue struct {
	ID               uint64 `protobuf:"varint,1,opt,name=id" json:"id"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadContinue) Reset()                    { *m = UploadContinue{} }
func (m *UploadContinue) String() string            { return proto.CompactTextString(m) }
func (*UploadContinue) ProtoMessage()               {}
func (*UploadContinue) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{7} }

func (m *UploadContinue) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type SysUsage struct {
	Mac              string `protobuf:"bytes,1,opt,name=mac" json:"mac"`
	CpuTotal         uint64 `protobuf:"varint,2,opt,name=CpuTotal" json:"CpuTotal"`
	MemTotal         uint64 `protobuf:"varint,3,opt,name=MemTotal" json:"MemTotal"`
	DiskTotal        uint64 `protobuf:"varint,4,opt,name=DiskTotal" json:"DiskTotal"`
	CpuUsedPercent   uint32 `protobuf:"varint,5,opt,name=CpuUsedPercent" json:"CpuUsedPercent"`
	MemUsedPercent   uint32 `protobuf:"varint,6,opt,name=MemUsedPercent" json:"MemUsedPercent"`
	DiskUsedPercent  uint32 `protobuf:"varint,7,opt,name=DiskUsedPercent" json:"DiskUsedPercent"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SysUsage) Reset()                    { *m = SysUsage{} }
func (m *SysUsage) String() string            { return proto.CompactTextString(m) }
func (*SysUsage) ProtoMessage()               {}
func (*SysUsage) Descriptor() ([]byte, []int) { return fileDescriptorPb, []int{8} }

func (m *SysUsage) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *SysUsage) GetCpuTotal() uint64 {
	if m != nil {
		return m.CpuTotal
	}
	return 0
}

func (m *SysUsage) GetMemTotal() uint64 {
	if m != nil {
		return m.MemTotal
	}
	return 0
}

func (m *SysUsage) GetDiskTotal() uint64 {
	if m != nil {
		return m.DiskTotal
	}
	return 0
}

func (m *SysUsage) GetCpuUsedPercent() uint32 {
	if m != nil {
		return m.CpuUsedPercent
	}
	return 0
}

func (m *SysUsage) GetMemUsedPercent() uint32 {
	if m != nil {
		return m.MemUsedPercent
	}
	return 0
}

func (m *SysUsage) GetDiskUsedPercent() uint32 {
	if m != nil {
		return m.DiskUsedPercent
	}
	return 0
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "pb.Heartbeat")
	proto.RegisterType((*InitUploadReq)(nil), "pb.InitUploadReq")
	proto.RegisterType((*InitUploadRsp)(nil), "pb.InitUploadRsp")
	proto.RegisterType((*UploadReq)(nil), "pb.UploadReq")
	proto.RegisterType((*UploadRsp)(nil), "pb.UploadRsp")
	proto.RegisterType((*UploadCompleteReq)(nil), "pb.UploadCompleteReq")
	proto.RegisterType((*UploadCompleteRsp)(nil), "pb.UploadCompleteRsp")
	proto.RegisterType((*UploadContinue)(nil), "pb.UploadContinue")
	proto.RegisterType((*SysUsage)(nil), "pb.SysUsage")
	proto.RegisterEnum("pb.Code", Code_name, Code_value)
	proto.RegisterEnum("pb.Cmd", Cmd_name, Cmd_value)
}
func (m *Heartbeat) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Heartbeat) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintPb(dAtA, i, uint64(len(m.Mac)))
	i += copy(dAtA[i:], m.Mac)
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *InitUploadReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitUploadReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Seq))
	dAtA[i] = 0x12
	i++
	i = encodeVarintPb(dAtA, i, uint64(len(m.ContentType)))
	i += copy(dAtA[i:], m.ContentType)
	dAtA[i] = 0x18
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ContentLength))
	dAtA[i] = 0x20
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ChunkCount))
	dAtA[i] = 0x28
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ModTime))
	dAtA[i] = 0x32
	i++
	i = encodeVarintPb(dAtA, i, uint64(len(m.Camera)))
	i += copy(dAtA[i:], m.Camera)
	dAtA[i] = 0x3a
	i++
	i = encodeVarintPb(dAtA, i, uint64(len(m.Mac)))
	i += copy(dAtA[i:], m.Mac)
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *InitUploadRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitUploadRsp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Seq))
	dAtA[i] = 0x10
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ID))
	dAtA[i] = 0x18
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Code))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UploadReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ID))
	dAtA[i] = 0x10
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Index))
	if m.Data != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintPb(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UploadRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadRsp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ID))
	dAtA[i] = 0x10
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Index))
	dAtA[i] = 0x18
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Code))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UploadCompleteReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadCompleteReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ID))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UploadCompleteRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadCompleteRsp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ID))
	dAtA[i] = 0x10
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.Code))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UploadContinue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadContinue) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.ID))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *SysUsage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SysUsage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintPb(dAtA, i, uint64(len(m.Mac)))
	i += copy(dAtA[i:], m.Mac)
	dAtA[i] = 0x10
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.CpuTotal))
	dAtA[i] = 0x18
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.MemTotal))
	dAtA[i] = 0x20
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.DiskTotal))
	dAtA[i] = 0x28
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.CpuUsedPercent))
	dAtA[i] = 0x30
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.MemUsedPercent))
	dAtA[i] = 0x38
	i++
	i = encodeVarintPb(dAtA, i, uint64(m.DiskUsedPercent))
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintPb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Heartbeat) Size() (n int) {
	var l int
	_ = l
	l = len(m.Mac)
	n += 1 + l + sovPb(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InitUploadReq) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.Seq))
	l = len(m.ContentType)
	n += 1 + l + sovPb(uint64(l))
	n += 1 + sovPb(uint64(m.ContentLength))
	n += 1 + sovPb(uint64(m.ChunkCount))
	n += 1 + sovPb(uint64(m.ModTime))
	l = len(m.Camera)
	n += 1 + l + sovPb(uint64(l))
	l = len(m.Mac)
	n += 1 + l + sovPb(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InitUploadRsp) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.Seq))
	n += 1 + sovPb(uint64(m.ID))
	n += 1 + sovPb(uint64(m.Code))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UploadReq) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.ID))
	n += 1 + sovPb(uint64(m.Index))
	if m.Data != nil {
		l = len(m.Data)
		n += 1 + l + sovPb(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UploadRsp) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.ID))
	n += 1 + sovPb(uint64(m.Index))
	n += 1 + sovPb(uint64(m.Code))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UploadCompleteReq) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.ID))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UploadCompleteRsp) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.ID))
	n += 1 + sovPb(uint64(m.Code))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UploadContinue) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovPb(uint64(m.ID))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SysUsage) Size() (n int) {
	var l int
	_ = l
	l = len(m.Mac)
	n += 1 + l + sovPb(uint64(l))
	n += 1 + sovPb(uint64(m.CpuTotal))
	n += 1 + sovPb(uint64(m.MemTotal))
	n += 1 + sovPb(uint64(m.DiskTotal))
	n += 1 + sovPb(uint64(m.CpuUsedPercent))
	n += 1 + sovPb(uint64(m.MemUsedPercent))
	n += 1 + sovPb(uint64(m.DiskUsedPercent))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovPb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozPb(x uint64) (n int) {
	return sovPb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Heartbeat) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Heartbeat: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Heartbeat: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitUploadReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitUploadReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitUploadReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentLength", wireType)
			}
			m.ContentLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContentLength |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChunkCount", wireType)
			}
			m.ChunkCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChunkCount |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModTime", wireType)
			}
			m.ModTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Camera", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Camera = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitUploadRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitUploadRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitUploadRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadCompleteReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadCompleteReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadCompleteReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadCompleteRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadCompleteRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadCompleteRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UploadContinue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadContinue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadContinue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SysUsage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SysUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SysUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CpuTotal", wireType)
			}
			m.CpuTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CpuTotal |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemTotal", wireType)
			}
			m.MemTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemTotal |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskTotal", wireType)
			}
			m.DiskTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiskTotal |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CpuUsedPercent", wireType)
			}
			m.CpuUsedPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CpuUsedPercent |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemUsedPercent", wireType)
			}
			m.MemUsedPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MemUsedPercent |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiskUsedPercent", wireType)
			}
			m.DiskUsedPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiskUsedPercent |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthPb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowPb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipPb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthPb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPb   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pb.proto", fileDescriptorPb) }

var fileDescriptorPb = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x5b, 0x4e, 0xdb, 0x4c,
	0x14, 0xc7, 0xe3, 0x4b, 0x6e, 0x07, 0x12, 0x86, 0xf3, 0xe5, 0x6b, 0x2d, 0x54, 0x85, 0xc8, 0xad,
	0x2a, 0x84, 0x50, 0x90, 0xba, 0x84, 0x98, 0x4a, 0x20, 0x15, 0xb5, 0x4a, 0x40, 0x7d, 0x76, 0x3c,
	0x23, 0x63, 0x11, 0x5f, 0xf0, 0x8c, 0x2b, 0xd8, 0x41, 0x57, 0x50, 0x75, 0x1f, 0xdd, 0x04, 0x8f,
	0xac, 0x00, 0xb5, 0xe9, 0x22, 0xfa, 0x5a, 0xcd, 0xd8, 0x0e, 0x4e, 0x28, 0x50, 0xf5, 0xc9, 0x3e,
	0xff, 0xff, 0x6f, 0xce, 0x65, 0x7c, 0x0c, 0xad, 0x64, 0x3a, 0x4c, 0xd2, 0x58, 0xc4, 0xa8, 0x27,
	0xd3, 0xad, 0x9e, 0x1f, 0xfb, 0xb1, 0x0a, 0xf7, 0xe5, 0x5b, 0xee, 0xd8, 0x2f, 0xa1, 0x7d, 0xc8,
	0xdc, 0x54, 0x4c, 0x99, 0x2b, 0xf0, 0x19, 0x18, 0xa1, 0xeb, 0x59, 0xda, 0x40, 0xdb, 0x69, 0x8f,
	0xcc, 0xeb, 0xdb, 0xed, 0xda, 0x58, 0x0a, 0xf6, 0x2f, 0x0d, 0x3a, 0x47, 0x51, 0x20, 0x4e, 0x93,
	0x59, 0xec, 0xd2, 0x31, 0xbb, 0x90, 0x24, 0x67, 0x17, 0x8a, 0x34, 0x4b, 0x92, 0xb3, 0x0b, 0x7c,
	0x0d, 0x6b, 0x5e, 0x1c, 0x09, 0x16, 0x89, 0x93, 0xab, 0x84, 0x59, 0x7a, 0x25, 0x53, 0xd5, 0xc0,
	0x5d, 0xe8, 0x14, 0xe1, 0x3b, 0x16, 0xf9, 0xe2, 0xcc, 0x32, 0x06, 0xda, 0x8e, 0x51, 0x90, 0xcb,
	0x16, 0xbe, 0x02, 0xf0, 0xce, 0xb2, 0xe8, 0xdc, 0x89, 0xb3, 0x48, 0x58, 0xe6, 0x40, 0xdb, 0xa9,
	0x17, 0x60, 0x45, 0xc7, 0x3e, 0x34, 0xc3, 0x98, 0x9e, 0x04, 0x21, 0xb3, 0xea, 0x95, 0x5c, 0xa5,
	0x88, 0x2f, 0xa0, 0xe1, 0xb9, 0x21, 0x4b, 0x5d, 0xab, 0x51, 0x69, 0xaa, 0xd0, 0xca, 0xc9, 0x9b,
	0xab, 0x93, 0xfb, 0x4b, 0x83, 0xf3, 0xe4, 0xc1, 0xc1, 0xb7, 0x40, 0x0f, 0xa8, 0x9a, 0xd7, 0x1c,
	0x81, 0x94, 0xe7, 0xb7, 0xdb, 0xfa, 0xd1, 0xc1, 0x58, 0x0f, 0x28, 0xda, 0x60, 0x7a, 0x31, 0x65,
	0x6a, 0xc6, 0xee, 0x9b, 0xd6, 0x30, 0x99, 0x0e, 0x9d, 0x98, 0xb2, 0xe2, 0xb8, 0xf2, 0xec, 0x8f,
	0xd0, 0xbe, 0xbb, 0xdd, 0x3c, 0x99, 0xf6, 0xc7, 0x64, 0x5b, 0x50, 0x0f, 0x22, 0xca, 0x2e, 0x55,
	0xad, 0xf2, 0x22, 0x72, 0x09, 0x11, 0x4c, 0xea, 0x0a, 0x57, 0x15, 0x5a, 0x1f, 0xab, 0x77, 0xdb,
	0x5f, 0x24, 0xe6, 0xc9, 0x3f, 0x27, 0xfe, 0x9b, 0x09, 0xf6, 0x61, 0x33, 0x2f, 0xe4, 0xc4, 0x61,
	0x32, 0x63, 0x82, 0x3d, 0x31, 0x89, 0x3d, 0xb9, 0x77, 0xe0, 0x89, 0x0e, 0xcb, 0x2e, 0xf4, 0x47,
	0xba, 0xd8, 0x83, 0x6e, 0x99, 0x34, 0x12, 0x41, 0x94, 0xb1, 0x47, 0x5b, 0xf8, 0xa2, 0x43, 0x6b,
	0x72, 0xc5, 0x4f, 0xb9, 0xeb, 0xb3, 0x87, 0xb6, 0x1f, 0x07, 0xd0, 0x72, 0x92, 0xec, 0x24, 0x16,
	0xee, 0xac, 0xf8, 0xc0, 0xb9, 0xb9, 0x50, 0x25, 0x71, 0xcc, 0xc2, 0x9c, 0x30, 0xaa, 0x44, 0xa9,
	0xa2, 0x0d, 0xed, 0x83, 0x80, 0x9f, 0xe7, 0x88, 0x59, 0x41, 0xee, 0x64, 0xdc, 0x83, 0xae, 0x93,
	0x64, 0xa7, 0x9c, 0xd1, 0x0f, 0x2c, 0xf5, 0x58, 0x24, 0xd4, 0x22, 0x77, 0x0a, 0x70, 0xc5, 0x93,
	0xf4, 0x31, 0x0b, 0xab, 0x74, 0xa3, 0x4a, 0x2f, 0x7b, 0x38, 0x84, 0x0d, 0x59, 0xa8, 0x8a, 0x37,
	0x2b, 0xf8, 0xaa, 0xb9, 0xfb, 0x59, 0x03, 0x53, 0xde, 0x2d, 0xae, 0x43, 0x4b, 0x3e, 0x27, 0x99,
	0xe7, 0x91, 0x5a, 0x19, 0x8d, 0x32, 0x7e, 0x45, 0x34, 0xdc, 0x80, 0x35, 0x19, 0x1d, 0x07, 0x9c,
	0x07, 0x91, 0x4f, 0x74, 0xec, 0x01, 0x91, 0xc2, 0x51, 0xf4, 0xc9, 0x9d, 0x05, 0xd4, 0x91, 0x3f,
	0x27, 0x31, 0xf0, 0x39, 0xfc, 0xb7, 0xa4, 0x32, 0xef, 0x9c, 0x67, 0x21, 0x31, 0x91, 0xc0, 0xba,
	0x34, 0xde, 0x4f, 0x26, 0x6f, 0xd3, 0x34, 0x4e, 0x49, 0x1d, 0x11, 0xba, 0x2a, 0xa3, 0x7b, 0x39,
	0x66, 0x22, 0x0d, 0x18, 0x27, 0x8d, 0xdd, 0x6f, 0x1a, 0x18, 0x4e, 0x48, 0xb1, 0x0d, 0x75, 0x27,
	0xa4, 0x87, 0x23, 0x52, 0xc3, 0x4d, 0xe8, 0x38, 0x21, 0xcd, 0xbf, 0xb3, 0xfc, 0x3d, 0x89, 0xa6,
	0x4a, 0x57, 0xa5, 0x31, 0x4f, 0x88, 0x8e, 0x1d, 0x68, 0x2f, 0x54, 0x62, 0xa8, 0x82, 0x65, 0x28,
	0x01, 0x13, 0xff, 0x87, 0xcd, 0x85, 0x52, 0xae, 0x21, 0xa9, 0xa3, 0x05, 0xbd, 0x7b, 0xb2, 0x3c,
	0xd0, 0x58, 0x39, 0x90, 0xaf, 0x18, 0x69, 0xaa, 0xab, 0x08, 0x69, 0xb9, 0x4a, 0xa4, 0x35, 0xea,
	0xdd, 0xfc, 0xe8, 0xd7, 0xae, 0xe7, 0x7d, 0xed, 0x66, 0xde, 0xd7, 0xbe, 0xcf, 0xfb, 0xda, 0xd7,
	0x9f, 0xfd, 0xda, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0xd1, 0xd0, 0x40, 0x92, 0x05, 0x00,
	0x00,
}
